FROM amazoncorretto:17-alpine

WORKDIR /opt/rdf-delta
COPY rdf-delta-fuseki-server-2.0.0-SNAPSHOT.jar rdf-delta-fuseki-server.jar

CMD ["java", "-jar", "/opt/rdf-delta/rdf-delta-fuseki-server.jar", "--conf", "/fuseki/config.ttl"]
