# Use python image as base image
FROM python:3.12

# Set working directory in the container
WORKDIR /app

# Copy the source code to the container
COPY src/ /app
COPY pyproject.toml /app

# Install poetry
RUN pip install poetry

# Install dependencies using poetry
RUN poetry config virtualenvs.create false && poetry install

# Set the entrypoint
ENTRYPOINT uvicorn consumer:app --host=${HOST:-0.0.0.0} --port=${PORT:-8080} --proxy-headers
